name: Debug Unit Test on PR
on:
  workflow_call:

jobs:
  run_tests:
    name: Testing debug variant
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name:  Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Execute Gradle testDebugUnitTest
        run: ./gradlew testDebugUnitTest
