name: Lint debug
on:
  workflow_call:

jobs:
  lint:
    name: Linting debug
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Execute Gradle lintDebug
        run: ./gradlew lintDebug
