name: On Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Debug Variant
    uses: ./.github/workflows/lint-debug.yml

  test:
    name: Test Debug Variant
    uses: ./.github/workflows/debug-unit-tests.yml
